spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
graphql:
  servlet:
    corsEnabled: true
    cors:
      allowed-origins:
        - '*'
      allow-credentials: true
      allowed-methods:
        - '*'
      allowed-headers:
        - '*'
