DROP TABLE IF EXISTS REPLY;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS RESTAURANT;

CREATE TABLE RESTAURANT (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  ADDRESS VARCHAR(250) NOT NULL,
  CITY VARCHAR(100) NOT NULL
);

CREATE TABLE REVIEW (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  MESSAGE VARCHAR(500) NOT NULL,
  RATING INT(1) NOT NULL,
  RESTAURANT_ID INT NOT NULL,
  CONSTRAINT `RESTAURANT_REVIEW_FK` FOREIGN KEY (`RESTAURANT_ID`) REFERENCES `RESTAURANT` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE REPLY (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  MESSAGE VARCHAR(500) NOT NULL,
  REVIEW_ID INT NOT NULL,
  CONSTRAINT `COMMENT_REVIEW_FK` FOREIGN KEY (`REVIEW_ID`) REFERENCES `REVIEW` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);
